In [1]:
import torch

In [14]:
ckpt = torch.load("last.ckpt", weights_only=False)
ckpt

{'epoch': 149,
 'global_step': 4200,
 'pytorch-lightning_version': '2.4.0',
 'state_dict': OrderedDict([('mel.0.kernel',
               tensor([[[-0.0000, -0.0001, -0.0003,  ..., -0.0000, -0.0000, -0.0000]],
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000]],
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000]],
               
                       ...,
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000]],
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000]],
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0012, -0.0000, -0.0000]]],
                      device='cuda:0')),
              ('mel.1.spectrogram.window',
               tensor([0.0000e+00, 1.0431e-06, 4.1723e-06,  ..., 9.4175e-06, 4.1723e-06,
                       1.0431e-06], device='cuda:0')),
    

In [15]:
f = torch.load("epoch=149-step=4200.ckpt", weights_only=False)
f

{'epoch': 149,
 'global_step': 4200,
 'pytorch-lightning_version': '2.4.0',
 'state_dict': OrderedDict([('mel.0.kernel',
               tensor([[[-0.0000, -0.0001, -0.0003,  ..., -0.0000, -0.0000, -0.0000]],
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000]],
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000]],
               
                       ...,
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000]],
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0000, -0.0000, -0.0000]],
               
                       [[-0.0000, -0.0000, -0.0000,  ..., -0.0012, -0.0000, -0.0000]]],
                      device='cuda:0')),
              ('mel.1.spectrogram.window',
               tensor([0.0000e+00, 1.0431e-06, 4.1723e-06,  ..., 9.4175e-06, 4.1723e-06,
                       1.0431e-06], device='cuda:0')),
    

RuntimeError: Boolean value of Tensor with more than one value is ambiguous